version: '3'

services:
  hitch:
    image: zazukoians/hitch
    ports:
      - 443:443
    volumes:
      - ./hitch/*.localhost.reachdigital.io.pem:/etc/ssl/hitch/combined.pem:ro
    environment:
      HITCH_PARAMS: --backend=[varnish]:80 --frontend=[*]:443 --alpn-protos="h2,http/1.1" --write-proxy

  varnish:
    image: hermsi/alpine-varnish
    volumes:
      - ./varnish/default.vcl:/etc/varnish/default.vcl:ro
    ports:
      - 6081:6081 # bin/magento setup:config:set --http-cache-hosts=127.0.0.1:6081
    environment:
      VARNISH_PORT: 80,PROXY
      VARNISHD_ADDITIONAL_OPTS: -p feature=+http2 -a :6081
      VARNISHLOG: 'true'

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.template:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ../src:/var/www/data:ro
    environment:
      FPM_PORT: 9000
      FPM_ROOT: '/Users/paulhachmang/Sites/iosr/src/pub'
    command: /bin/sh -c "envsubst '$$FPM_PORT $$FPM_ROOT' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"

  db:
    image: percona:5.7
    ports:
      - 3306:3306
    environment: 
      MYSQL_ROOT_PASSWORD: magento
      MYSQL_DATABASE: magento
      MYSQL_USER: magento
      MYSQL_PASSWORD: magento
    volumes:
      - ./.mysql:/var/lib/mysql

  redis:
    image: redis:5.0

#  elasticsearch:
#    image: mage2click/magento-elasticsearch:6.7.2
#    ports:
#      - "9200:9200"
#      - "9300:9300"
#    volumes:
#      - esdata:/usr/share/elasticsearch/data
#
#  mailhog:
#    image: mailhog/mailhog:v1.0.0
#    ports:
#      - "1025:1025"
#      - "8025:8025"
#
#  rabbitmq:
#    image: rabbitmq:3.7.14-management-alpine
#    ports:
#      - "5672:5672"
#      - "15672:15672"
#
#  cron:
#    image: mage2click/magento-php-versions:7.1-fpm
#    user: root
#    command: /usr/local/bin/cronstart
#    tty: true
#    volumes: *appvolumes
#
#volumes:
#  appdata:
#  dbdata:
#  esdata:
#  sockdata:
